name: Build & Push to Github Packages
on:
  push:
    branches:
      - master

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build --tag "docker.pkg.github.com/nikodemwrona/ncrow-dev/ncrow-dev:latest" .
        working-directory: .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push "docker.pkg.github.com/nikodemwrona/ncrow-dev/ncrow-dev:latest"

      - name: Deploy ncrow-dev
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.DEPLOY_COMMAND }}
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          privateKey: ${{ secrets.SECRET_KEY }}

